name: canteen
description: "Shop App for campus canteen"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  auto_route: ^10.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.13
  get_it: ^8.0.2
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  chat_bubbles: ^1.7.0
  table_calendar: ^3.0.9
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/layouts/
    - assets/product_images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic